"""empty message

Revision ID: 04076a273782
Revises: 
Create Date: 2018-06-03 00:16:39.770262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04076a273782'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cnns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('c_name', sa.String(length=32), nullable=True),
    sa.Column('c_type', sa.String(length=16), nullable=True),
    sa.Column('c_format', sa.String(length=16), nullable=True),
    sa.Column('c_path', sa.String(length=64), nullable=True),
    sa.Column('c_isPublic', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('d_name', sa.String(length=32), nullable=True),
    sa.Column('d_type', sa.String(length=16), nullable=True),
    sa.Column('d_size', sa.String(length=16), nullable=True),
    sa.Column('d_path', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hosts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('h_ip', sa.String(length=16), nullable=True),
    sa.Column('h_os', sa.String(length=64), nullable=True),
    sa.Column('h_username', sa.String(length=16), nullable=True),
    sa.Column('h_password', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('a_description', sa.String(length=64), nullable=True),
    sa.Column('a_level', sa.String(length=16), nullable=True),
    sa.Column('a_type', sa.String(length=32), nullable=True),
    sa.Column('a_modelId', sa.Integer(), nullable=True),
    sa.Column('a_dataId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['a_dataId'], ['data_sets.id'], ),
    sa.ForeignKeyConstraint(['a_modelId'], ['cnns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sample_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('s_description', sa.String(length=64), nullable=True),
    sa.Column('s_type', sa.String(length=32), nullable=True),
    sa.Column('s_modelClsId', sa.Integer(), nullable=True),
    sa.Column('s_modelDetId', sa.Integer(), nullable=True),
    sa.Column('s_dataId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['s_dataId'], ['data_sets.id'], ),
    sa.ForeignKeyConstraint(['s_modelClsId'], ['cnns.id'], ),
    sa.ForeignKeyConstraint(['s_modelDetId'], ['cnns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('t_description', sa.String(length=64), nullable=True),
    sa.Column('t_caseType', sa.String(length=16), nullable=True),
    sa.Column('t_hostId', sa.Integer(), nullable=True),
    sa.Column('t_apiCaseId', sa.Integer(), nullable=True),
    sa.Column('t_sampleCaseId', sa.Integer(), nullable=True),
    sa.Column('t_duration', sa.Integer(), nullable=True),
    sa.Column('t_status', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['t_apiCaseId'], ['api_cases.id'], ),
    sa.ForeignKeyConstraint(['t_hostId'], ['hosts.id'], ),
    sa.ForeignKeyConstraint(['t_sampleCaseId'], ['sample_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('r_description', sa.String(length=64), nullable=True),
    sa.Column('r_taskId', sa.Integer(), nullable=True),
    sa.Column('r_result', sa.Boolean(), nullable=True),
    sa.Column('r_errorLog', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['r_taskId'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    op.drop_table('tasks')
    op.drop_table('sample_cases')
    op.drop_table('api_cases')
    op.drop_table('hosts')
    op.drop_table('data_sets')
    op.drop_table('cnns')
    # ### end Alembic commands ###
